"use client";
import {useSession} from '../../lib/session';
import {defaultPreparationLevel,schoolTarget,preparationLevel} from '../../data/school-training';
import {technicalCatalogSource} from '../../data/technical-figures';
import {Dialog} from '../../components/ui/Dialog';
import {InstrumentIntroduction} from '../../components/domain/InstrumentIntroduction';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {PagedList} from '../../components/ui/PagedList';
import {Button,Card,Field,SelectField,PageHeader,Notice} from '../../components/ui/primitives';
import {useTraining,trainingApi,TrainingError,decimal} from './shared';
import {SimulatorRun,TrainingResult} from './SimulatorRun';
import {principalGrade} from '../../lib/training-engine';
import './training.css';
export function StudentCourses(){
 const {data:raw,error,busy,refresh,run}=useTraining();
 const profile=useSession().values['rv360:profile'];
 const [level,setLevel]=useState(defaultPreparationLevel(profile));
 useEffect(()=>setLevel(defaultPreparationLevel(profile)),[profile?.stage]);
 const d=raw?{...raw,careers:raw.careers.filter((c:any)=>(c.educationLevel||'universidad')===level),recommendations:raw.recommendations.filter((r:any)=>schoolTarget(r.careerId)===(level==='bachillerato')),attempts:raw.attempts.filter((a:any)=>preparationLevel(a.simulator?.careerIds,a.simulator?.educationLevel)===level),simulators:raw.simulators.filter((s:any)=>s.careerIds?.some((id:string)=>schoolTarget(id)===(level==='bachillerato')))}:null;
 const [starting,setStarting]=useState<{simulator:any;mode:string}|null>(null);
 const [career,setCareer]=useState(''),[query,setQuery]=useState(''),[active,setActive]=useState<any>(null),[result,setResult]=useState<any>(null);
 useEffect(()=>{if(!d)return;const id=new URLSearchParams(window.location.search).get('carrera');if(id&&raw?.recommendations.some((r:any)=>r.careerId===id)){setLevel(schoolTarget(id)?'bachillerato':'universidad');setCareer(id);}},[d?.recommendations?.map((r:any)=>r.careerId).join(',')]);
 const [area,setArea]=useState(''),[state,setState]=useState(''),[historyQuery,setHistoryQuery]=useState('');
 const match=(text:string,q:string)=>text.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(q.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase());
 const choose=(id:string)=>{setCareer(id);setQuery('');setState('');setArea('');window.history.replaceState(null,'',id?'?carrera='+encodeURIComponent(id):window.location.pathname);};
 const attempts=(id:string)=>(d?.attempts||[]).filter((a:any)=>a.simulator.id===id);
 const simulators=(id:string)=>(d?.simulators||[]).filter((s:any)=>s.careerIds?.includes(id));
 const complete=(s:any)=>attempts(s.id).some((a:any)=>a.state==='graded');
 const selected=d?.recommendations.some((r:any)=>r.careerId===career)?d?.careers.find((c:any)=>c.id===career):null;
 const access=raw?.readiness?.[level];
 if(raw&&!access?.ready)return <div className="training"><PageHeader title="Completa tus tests para acceder a los cursos" description="Tu preparación se habilita cuando completas los tests de esta ruta y sus resultados están publicados."/><nav className="ar-tabs" aria-label="Nivel de preparación"><Button variant={level==='bachillerato'?'primary':'secondary'} aria-pressed={level==='bachillerato'} onClick={()=>{setLevel('bachillerato');choose('');}}>Bachillerato</Button><Button variant={level==='universidad'?'primary':'secondary'} aria-pressed={level==='universidad'} onClick={()=>{setLevel('universidad');choose('');}}>Universidad</Button></nav><TrainingError error={error} retry={refresh}/><Card className="stack"><h2>{level==='bachillerato'?'Bachillerato':'Universidad'}: tests pendientes</h2><p role="status">{access?.completed||0} de {access?.total||0} tests completos con resultados publicados.</p>{access?.pending?.length>0?<ul>{access.pending.map((t:any)=><li key={t.id}><strong>{t.title}</strong> · {t.state==='awaiting_results'?'En revisión: espera la publicación':t.state==='in_progress'?'En curso':t.state==='insufficient'?'Necesita respuestas completas':'Pendiente de realizar'}</li>)}</ul>:<p>Tu institución debe asignar tests para habilitar tu orientación.</p>}<p>Cuando estén listos, aquí aparecerá la preparación relacionada con tus resultados.</p><Link className="button button--primary" href="/mi-ruta/evaluaciones">Ir a mis tests</Link></Card></div>;
 if(active)return <div className="training"><SimulatorRun initial={active} onClose={()=>{setActive(null);void refresh();}}/></div>;
 if(result)return <div className="training"><Button variant="secondary" onClick={()=>setResult(null)}>Volver a mis simuladores</Button><TrainingResult attempt={result}/></div>;
 return <div className="training"><PageHeader title={selected?'Autopreparación para '+selected.name:level==='bachillerato'?'Explora y prepara tu bachillerato':'Tu preparación universitaria'} description={selected?'Practica con los simuladores de esta opción. Obtén tu nota al entregar y consulta tus avances.':level==='bachillerato'?'Compara opciones para entrar a BGU sin elegir una carrera universitaria.':'Elige una de las carreras recomendadas por tus tests para comenzar a practicar.'}/><nav className="ar-tabs" aria-label="Nivel de preparación"><Button variant={level==='bachillerato'?'primary':'secondary'} onClick={()=>{setLevel('bachillerato');choose('');}}>Bachillerato</Button><Button variant={level==='universidad'?'primary':'secondary'} onClick={()=>{setLevel('universidad');choose('');}}>Universidad</Button></nav>{level==='bachillerato'&&<Notice>Para pasar de EGB Superior a primero de BGU. Explora Ciencias y Técnico, sus áreas y figuras profesionales; después practica los contenidos publicados por tu institución. La disponibilidad de una figura se confirma con cada colegio. <a href={technicalCatalogSource.url} target="_blank" rel="noreferrer">Consultar catálogo oficial</a></Notice>}<TrainingError error={error} retry={refresh}/><Dialog open={!!starting} title={starting?.mode==='exam'?'Antes de iniciar el examen':'Antes de iniciar la práctica'} onClose={()=>{if(!busy)setStarting(null);}}><div className="stack">{error&&<Notice tone="danger">{error}</Notice>}<h3>{starting?.simulator.title}</h3><p>{starting?.simulator.questionCount} preguntas · Nota sobre 100 puntos</p><p>{starting?.mode==='exam'?'Tiempo disponible: '+starting.simulator.durationMinutes+' minutos. El reloj continúa aunque salgas de la página y el intento se entrega al terminar el tiempo.':starting?.simulator.practiceDurationMinutes?'Tiempo de práctica: '+starting.simulator.practiceDurationMinutes+' minutos.':'Práctica sin límite de tiempo. Puedes guardar y continuar.'}</p><p>Las respuestas se califican con las claves del simulador. Puedes revisar las preguntas antes de entregar. Esta actividad es de preparación y no emite un puntaje oficial de admisión.</p><div className="training-actions"><Button variant="secondary" disabled={busy} onClick={()=>setStarting(null)}>Volver</Button><Button loading={busy} onClick={()=>{if(starting)void run(async()=>{setActive(await trainingApi('/simulator/start',{simulatorId:starting.simulator.id,mode:starting.mode}));setStarting(null);}).catch(()=>{});}}>{starting?.mode==='exam'?'Comenzar examen':'Comenzar práctica'}</Button></div></div></Dialog>{!d&&!error&&<p role="status">Cargando tu preparación…</p>}{d&&<>
 {selected?<><Button variant="secondary" onClick={()=>choose('')}>Volver a mis opciones</Button><div className="training-summary"><div><strong>{simulators(career).length}</strong><p>Simuladores disponibles</p></div><div><strong>{simulators(career).filter(complete).length}</strong><p>Simuladores completados</p></div><div><strong>{simulators(career).length?Math.round(simulators(career).filter(complete).length/simulators(career).length*100):0}%</strong><p>Progreso de preparación</p></div></div><div className="preparation-filters"><Field label="Buscar simulador" type="search" value={query} onChange={e=>setQuery(e.target.value)}/><SelectField label="Estado de preparación" value={state} onChange={e=>setState(e.target.value)}><option value="">Todos los estados</option><option value="pending">Sin comenzar</option><option value="progress">En curso</option><option value="done">Completado</option></SelectField></div>
 {!simulators(career).length&&<Notice>La preparación de esta opción aún no tiene simuladores publicados. Aparecerán aquí cuando administración los publique.</Notice>}
 <PagedList className="training-grid" label="simuladores" resetKey={career+query+state}>{simulators(career).filter((s:any)=>match(s.title,query)&&(!state||(state==='done'?complete(s):state==='progress'?attempts(s.id).some((a:any)=>a.state==='in_progress'):!attempts(s.id).length))).map((s:any)=>{const rows=attempts(s.id),graded=rows.filter((a:any)=>a.result?.percent!=null);return <Card key={s.id}><small>Autocalificable · Versión {s.version}</small><h2>{s.title}</h2><InstrumentIntroduction instrument={s.instrument}/><p>{s.questionCount} preguntas · Examen: {s.durationMinutes} minutos</p>{s.modes.map((mode:string)=>{const history=rows.filter((a:any)=>a.mode===mode),open=history.find((a:any)=>a.state==='in_progress'),scores=history.filter((a:any)=>a.result?.percent!=null).map((a:any)=>a.result.percent);return <div className="simulator-mode" key={mode}><div><b>{mode==='exam'?'Examen cronometrado':'Práctica'}</b><p>{scores.length?'Nota: '+decimal(principalGrade(scores,s.gradePolicy))+' / 100':'Todavía sin nota'} · {history.length} / {s.maxAttempts} intentos</p></div><Button disabled={busy||!open&&history.length>=s.maxAttempts} onClick={()=>open?run(async()=>setActive(await trainingApi('/simulator/start',{simulatorId:s.id,mode}))).catch(()=>{}):setStarting({simulator:s,mode})}>{open?'Continuar':mode==='exam'?'Iniciar examen':'Practicar'}</Button></div>;})}{graded.length>0&&<details><summary>Mis notas y respuestas · {graded.length} entregas</summary>{[...graded].reverse().map((a:any)=><div className="simulator-grade" key={a.id}><span>{a.mode==='exam'?'Examen':'Práctica'} · {new Date(a.finished_at).toLocaleDateString('es-EC')} · <b>{decimal(a.result.percent)} / 100</b></span><Button variant="ghost" onClick={()=>setResult(a)}>Ver resultado</Button></div>)}</details>}</Card>;})}</PagedList></>:<>
 {!d.recommendations.length?<Card><h2>Todavía no hay preparación relacionada</h2><p>Tus tests están completos. Aún no hay opciones relacionadas con evidencia suficiente para esta ruta. Revisa tus resultados con tu orientador.</p><Link className="button button--primary" href="/mi-ruta/evaluaciones">Ir a mis tests</Link></Card>:<><div className="preparation-filters"><Field label="Buscar opción de estudio" type="search" value={query} onChange={e=>setQuery(e.target.value)}/><SelectField label="Área de estudio" value={area} onChange={e=>setArea(e.target.value)}><option value="">Todas las áreas</option>{Array.from(new Set<string>(d.careers.map((c:any)=>c.area))).sort().map(a=><option key={a}>{a}</option>)}</SelectField><SelectField label="Disponibilidad" value={state} onChange={e=>setState(e.target.value)}><option value="">Todas mis opciones</option><option value="available">Con simuladores</option><option value="done">Con avances</option><option value="empty">Sin simuladores aún</option></SelectField></div><PagedList className="training-grid preparation-careers" label="opciones de estudio" resetKey={query+area+state}>{d.recommendations.filter((r:any)=>{const c=d.careers.find((c:any)=>c.id===r.careerId);return c&&match(c.name,query)&&(!area||c.area===area)&&(!state||(state==='available'?simulators(c.id).length>0:state==='done'?simulators(c.id).some(complete):!simulators(c.id).length));}).map((r:any)=>{const c=d.careers.find((c:any)=>c.id===r.careerId);if(!c)return null;const list=simulators(c.id),done=list.filter(complete).length;return <Card key={c.id}><small>{level==='bachillerato'?(r.suggested?'Relacionada con tus intereses':'Opción para explorar'):'Carrera recomendada'} · {c.area}</small><h2>{c.name}</h2><details className="career-reason"><summary>Por qué aparece esta opción</summary><p>{r.reason}</p></details><p>{list.length} simuladores disponibles · {done} completados</p><progress aria-label={'Progreso en '+c.name} max={Math.max(1,list.length)} value={done}/><Button onClick={()=>choose(c.id)}>Autopreparación</Button></Card>;})}</PagedList></>}
 </>}
 <details className="simulator-history"><summary>Historial de notas · {d.attempts.filter((a:any)=>a.result).length} entregas</summary><Field label="Buscar en mis notas" type="search" value={historyQuery} onChange={e=>setHistoryQuery(e.target.value)}/><PagedList className="stack" label="resultados" resetKey={historyQuery}>{d.attempts.filter((a:any)=>a.result&&match(a.instrument.title,historyQuery)).map((a:any)=><div className="simulator-grade" key={a.id}><span>{a.instrument.title} · {a.result.percent!=null?decimal(a.result.percent)+' / 100':'Pendiente'}</span><Button variant="secondary" onClick={()=>setResult(a)}>Ver resultado</Button></div>)}</PagedList></details>
 </>}</div>;
}
