// Public academic material only. No dependency on identity, profiles or submissions.
import {readFileSync,writeFileSync,mkdirSync,renameSync,openSync,closeSync,unlinkSync,statSync} from 'node:fs';
import {resolve,dirname} from 'node:path';
import {createHash} from 'node:crypto';
export const ACADEMIC_VERSION='public-academic-2',MAPPING_VERSION='exploration-rules-1';
export const areas=[
 {id:'salud',name:'Salud y cuidado',pattern:'MEDICINA|ENFERMER|ODONTO|NUTRICI|FISIOTER|TERAPIA|OBSTETR',dimensions:['I','S'],contrast:'Ciencias biológicas y atención a personas; investiga prácticas clínicas y condiciones de trabajo.'},
 {id:'ciencias',name:'Ciencias e investigación',pattern:'BIOLOG|QUIMICA|FISICA|MATEMAT|ESTADIST|BIOTEC|GEOLOG',dimensions:['I','R'],contrast:'Observación, experimentación y razonamiento cuantitativo; compara trabajo de laboratorio y campo.'},
 {id:'tecnologia',name:'Computación y tecnología',pattern:'SOFTWARE|COMPUTA|INFORMAT|SISTEMAS|DATOS|INTELIGENCIA ARTIFICIAL|CIBER',dimensions:['I','R'],contrast:'Resolución de problemas y construcción de sistemas; prueba una actividad de programación.'},
 {id:'ingenieria',name:'Ingeniería y producción',pattern:'INGENIER|MECANIC|ELECTR|INDUSTRIAL|AUTOMOT|MECATR|CIVIL|TELECOM',dimensions:['R','I'],contrast:'Diseño, cálculo y funcionamiento de sistemas físicos; revisa matemáticas, proyectos y prácticas.'},
 {id:'ambiente',name:'Ambiente y territorio',pattern:'AMBIENT|AGRO|FOREST|VETERIN|ZOOTEC|ACUIC|PESCA|RECURSOS NATURALES',dimensions:['R','I'],contrast:'Sistemas naturales y producción sostenible; explora actividades de campo y laboratorio.'},
 {id:'educacion',name:'Educación y acompañamiento',pattern:'EDUCACI|PEDAGOG|PSICOLOG|TRABAJO SOCIAL|PSICOPEDAG',dimensions:['S','I'],contrast:'Aprendizaje y acompañamiento de personas; diferencia docencia, intervención e investigación.'},
 {id:'arte',name:'Arte, diseño y comunicación',pattern:'DISENO|ARTES|MUSICA|CINE|COMUNICACI|PUBLICIDAD|ANIMACI|ARQUITECT|PERIODIS',dimensions:['A','E'],contrast:'Creación y comunicación; compara producción artística, diseño aplicado y comunicación informativa.'},
 {id:'humanidades',name:'Humanidades y sociedad',pattern:'FILOSOF|HISTORIA|LITERAT|SOCIOLOG|ANTROPOLOG|LENGUA|DERECHO|RELACIONES INTERNACIONALES|CIENCIAS POLITICAS',dimensions:['S','A'],contrast:'Lectura, argumentación y análisis social; compara investigación, servicio público y ejercicio profesional.'},
 {id:'negocios',name:'Economía y organizaciones',pattern:'ADMINISTR|ECONOM|FINANZ|CONTAB|COMERC|NEGOC|MARKETING|MERCAD|LOGIST|GESTION',dimensions:['E','C'],contrast:'Decisiones, organización y recursos; diferencia análisis financiero, gestión y relaciones comerciales.'},
 {id:'servicios',name:'Turismo, deporte y servicios',pattern:'TURIS|HOTEL|GASTRONOM|DEPORTE|ENTRENAMIENTO|ACTIVIDAD FISICA',dimensions:['S','E'],contrast:'Experiencias y servicios para personas; investiga horarios, práctica y actividades cotidianas.'}
];
const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase();
export const degreeOffer=o=>/UNIVERSIDAD|POLITECNICA/.test(normalize(o.institution))&&!/TECNOLOG|TECNICO|MAGISTER|ESPECIALISTA|MAESTR/.test(normalize(o.title));
export const areaFor=name=>areas.find(a=>new RegExp(a.pattern).test(normalize(name)));
export function publicCatalog(){const d=JSON.parse(readFileSync(resolve('lib/server/data/ecuador-offer.json'),'utf8'));if(d.careerCount!==d.careers.length||d.offerCount!==d.careers.reduce((n,c)=>n+c.offers.length,0)||new Set(d.careers.map(c=>c.id)).size!==d.careerCount)throw Error('CATALOG_INVALID');return d;}
const sha=v=>createHash('sha256').update(JSON.stringify(v)).digest('hex'),cachePath=()=>resolve(/*turbopackIgnore: true*/ process.env.ACADEMIC_CONTENT_PATH||'storage/academic-content.json');
export function academicInput(){const c=publicCatalog();return {version:ACADEMIC_VERSION,catalogSource:{url:c.sourceUrl,version:c.sha256},categories:areas.map(a=>({id:a.id,name:a.name,theoreticalInterests:a.dimensions,comparison:a.contrast,careerExamples:c.careers.filter(c=>areaFor(c.name)?.id===a.id&&c.offers.some(degreeOffer)).slice(0,3).map(c=>({id:c.id,name:c.name}))}))};}
export const academicPrompt='Redacta contenido académico GENERAL compartido para estudiantes que conectan su bachillerato con opciones universitarias en Ecuador. No existe un estudiante en esta solicitud. No evalúes ni personalices. Devuelve todas las categorías exactamente una vez con su id, una explicación breve de qué se estudia y dos preguntas para comparar opciones. Usa únicamente las áreas y denominaciones proporcionadas; no añadas universidades, requisitos, costos, cupos, cifras, porcentajes ni garantías. No confundas intereses RIASEC con capacidades medidas. No afirmes validación científica del cuestionario local. Evita consejos deterministas. JSON según esquema, español claro. No incluyas campos adicionales.';
export const academicSchema={type:'object',additionalProperties:false,required:['categories'],properties:{categories:{type:'array',items:{type:'object',additionalProperties:false,required:['id','explanation','questions'],properties:{id:{type:'string',enum:areas.map(a=>a.id)},explanation:{type:'string'},questions:{type:'array',items:{type:'string'}}}}}}};
export function validateAcademic(v){const text=s=>typeof s==='string'&&s.length>=15&&s.length<=1300&&!/https?:|@|\d|%|debes estudiar|tu carrera ideal|garantiz|universidad de/iu.test(s);if(!v||Object.keys(v).join()!=='categories'||!Array.isArray(v.categories)||v.categories.length!==areas.length)throw Error('CONTENT_INVALID');const ids=new Set();for(const c of v.categories){if(Object.keys(c).sort().join()!=='explanation,id,questions'||!areas.some(a=>a.id===c.id)||ids.has(c.id)||!text(c.explanation)||!Array.isArray(c.questions)||c.questions.length!==2||!c.questions.every(text))throw Error('CONTENT_INVALID');ids.add(c.id);}return v;}
export function localAcademic(){return {id:'local-'+ACADEMIC_VERSION,version:ACADEMIC_VERSION,source:'local',model:null,categories:areas.map(a=>({id:a.id,explanation:a.contrast,questions:['¿Qué asignaturas y actividades de esta área te gustaría probar?','¿Qué diferencias encuentras entre las mallas oficiales de dos carreras de esta área?']}))};}
export function readAcademic(){try{const r=JSON.parse(readFileSync(/*turbopackIgnore: true*/ cachePath(),'utf8'));if(r.inputHash!==sha(academicInput())||r.version!==ACADEMIC_VERSION)throw Error('STALE');validateAcademic({categories:r.categories});return r;}catch{return localAcademic();}}
function atomic(path,value){mkdirSync(dirname(path),{recursive:true});const t=path+'.'+process.pid+'.tmp';writeFileSync(t,JSON.stringify(value,null,2),{mode:0o600});renameSync(t,path);}
export async function refreshAcademicContent(){const cached=readAcademic();if(cached.source==='gemini')return {...cached,reused:true};const path=cachePath(),lock=path+'.lock';mkdirSync(dirname(path),{recursive:true});let fd;try{fd=openSync(lock,'wx');}catch{if(Date.now()-statSync(lock).mtimeMs>180000)unlinkSync(lock);throw Error('CONTENT_BUSY');}
 try{const model=process.env.GEMINI_MODEL||'gemini-3.1-flash-lite';if(!process.env.GEMINI_API_KEY?.trim())throw Error('GEMINI_CONFIGURATION');const headers={'x-goog-api-key':process.env.GEMINI_API_KEY,'Content-Type':'application/json'},input=academicInput(),payload={systemInstruction:{parts:[{text:academicPrompt}]},contents:[{role:'user',parts:[{text:JSON.stringify(input)}]}],generationConfig:{temperature:0.2,maxOutputTokens:6000,responseMimeType:'application/json',responseJsonSchema:academicSchema}};
 const usagePath=path+'.usage.json';let usage={day:new Date().toISOString().slice(0,10),requests:0};try{const old=JSON.parse(readFileSync(usagePath,'utf8'));if(old.day===usage.day)usage=old;}catch{}const limit=Math.min(20,Math.max(1,Number(process.env.AI_DAILY_REQUEST_LIMIT)||20));
 const info=await fetch('https://generativelanguage.googleapis.com/v1beta/models/'+model,{headers,signal:AbortSignal.timeout(15000)});if(!info.ok)throw Error([401,403].includes(info.status)?'PROVIDER_AUTH':info.status===429?'PROVIDER_QUOTA':'MODEL_UNAVAILABLE');const mi=await info.json();if(!mi.supportedGenerationMethods?.includes('generateContent'))throw Error('MODEL_UNSUPPORTED');
 for(let attempt=0;attempt<2;attempt++){if(usage.requests>=limit)throw Error('LOCAL_DAILY_LIMIT');usage.requests++;atomic(usagePath,usage);const response=await fetch('https://generativelanguage.googleapis.com/v1beta/models/'+model+':generateContent',{method:'POST',headers,body:JSON.stringify(payload),signal:AbortSignal.timeout(45000)});if(response.status===429){if(!attempt){await new Promise(r=>setTimeout(r,Math.min(5000,Math.max(1000,Number(response.headers.get('retry-after')||2)*1000))));continue;}throw Error('PROVIDER_QUOTA');}if(!response.ok)throw Error(response.status===401||response.status===403?'PROVIDER_AUTH':'PROVIDER_UNAVAILABLE');const data=await response.json(),candidate=data.candidates?.[0];if(candidate?.finishReason!=='STOP')throw Error('PROVIDER_INCOMPLETE');const content=validateAcademic(JSON.parse(candidate.content.parts.filter(p=>!p.thought).map(p=>p.text||'').join(''))),record={id:sha(content),version:ACADEMIC_VERSION,source:'gemini',model:data.modelVersion||model,createdAt:new Date().toISOString(),inputHash:sha(input),payloadHash:sha(payload),publicInput:input,usage:data.usageMetadata,validation:'schema-and-content-rules-v1',...content};atomic(path,record);atomic(path+'.evidence.json',{httpStatus:200,model:record.model,createdAt:record.createdAt,payload,inputHash:record.inputHash,contentHash:record.id,usage:record.usage,containsStudentData:false,billing:'Not modified. Account billing tier is not exposed by this API.'});return record;}throw Error('PROVIDER_QUOTA');
 }finally{if(fd!==undefined)closeSync(fd);unlinkSync(lock);}
}
