import {readDocumentMarkup} from '../../components/kit/lib/import-content.ts';
export {proposeTests} from '../../components/kit/lib/import-content.ts';
import { documentExtension, documentFileError } from '../../components/kit/lib/document-formats.ts';
import { decodeDocumentText, documentArchive, odtDocumentMarkup, plainDocumentText, rtfDocumentText } from './document-text.ts';
import { parseHTML } from 'linkedom';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { createDocumentOcr } from './document-ocr.ts';
function fail(message:string):never{throw new Error(message);}
export async function extractFile(bytes:Buffer,name:string,onProgress:(value:number)=>void=()=>{}){const fileError=documentFileError(name,bytes.length);if(fileError)fail(fileError);let text='',embedded:any[]=[];const warnings:string[]=[];const images:{src:string;alt:string;source:string}[]=[];const extension=documentExtension(name);
if(extension==='html'||extension==='htm'){if(!/<(?:!doctype|html|body|p|div|form|fieldset|ol|ul|table|script|pre|section|article|h[1-6])(?:\s|>)/i.test(decodeDocumentText(bytes)))fail('El archivo no contiene HTML reconocible.');const html=decodeDocumentText(bytes);const {document}=parseHTML(/<html[\s>]/i.test(html)?html:'<html><body>'+html+'</body></html>');const parsed=readDocumentMarkup(document);text=parsed.text;embedded=parsed.embedded;warnings.push(...parsed.warnings);
}else if(extension==='txt'||extension==='md'){text=plainDocumentText(bytes,extension==='md');
}else if(extension==='rtf'){text=rtfDocumentText(bytes);warnings.push('Se importó el texto del RTF. Revisa tablas, imágenes y numeración en el documento original.');
}else if(extension==='odt'){const {document}=parseHTML('<html><body>'+odtDocumentMarkup(bytes)+'</body></html>');const parsed=readDocumentMarkup(document);text=parsed.text;embedded=parsed.embedded;warnings.push(...parsed.warnings,'Se importaron párrafos, listas y tablas del ODT. Revisa imágenes y fórmulas en el documento original.');
}else if(extension==='docx'){const archive=documentArchive(bytes,'DOCX');if(!archive.has('word/document.xml')||!archive.has('[Content_Types].xml'))fail('El archivo no es un documento DOCX válido.');const mammoth=await import('mammoth');const converted=await mammoth.convertToHtml({buffer:bytes},{convertImage:mammoth.images.imgElement(async image=>{const data=await image.read('base64');if(!['image/png','image/jpeg','image/webp'].includes(image.contentType)||data.length>333336||images.length>=8){warnings.push('Una imagen de Word requiere revisión en el documento original por tamaño o formato.');return {src:'',alt:'Imagen disponible en el documento original'};}const src='data:'+image.contentType+';base64,'+data;images.push({src,alt:'',source:'Word · imagen '+(images.length+1)});return {src};})});const {document}=parseHTML('<html><body>'+converted.value+'</body></html>');const parsed=readDocumentMarkup(document);text=parsed.text;embedded=parsed.embedded;warnings.push(...parsed.warnings);if(images.length)warnings.push('Revisa las '+images.length+' imágenes extraídas de Word y asígnalas a sus preguntas desde el editor. No se asociaron automáticamente.');if(converted.messages.length)warnings.push('Word contiene elementos de formato que requieren contraste con el original.');
}else if(extension==='pdf'){if(bytes.subarray(0,5).toString()!=='%PDF-')fail('El archivo no es un PDF válido.');const canvas=await import('@napi-rs/canvas');Object.assign(globalThis,{DOMMatrix:canvas.DOMMatrix,ImageData:canvas.ImageData,Path2D:canvas.Path2D});const pdfjs=await import('pdfjs-dist/legacy/build/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc=pathToFileURL(resolve('node_modules/pdfjs-dist/legacy/build/pdf.worker.mjs')).href;const loading=pdfjs.getDocument({data:new Uint8Array(bytes),useSystemFonts:true});let worker:any;try{const pdf=await loading.promise;if(pdf.numPages>60)fail('Importa documentos de hasta 60 páginas.');for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i),content=await page.getTextContent();let pageText=content.items.map((item:any)=>item.str+(item.hasEOL?'\n':' ')).join('');if(pageText.trim().length<20){const viewport=page.getViewport({scale:1.5});if(viewport.width>10000||viewport.height>10000||viewport.width*viewport.height>20000000)fail('La página escaneada excede el tamaño permitido. Reduce su resolución antes de importar.');if(!worker)worker=await createDocumentOcr();const surface=canvas.createCanvas(Math.ceil(viewport.width),Math.ceil(viewport.height));await page.render({canvasContext:surface.getContext('2d') as any,canvas:surface as any,viewport}).promise;const recognized=(await worker.recognize(surface.toBuffer('image/png'))).data;pageText=recognized.text;warnings.push('Página '+i+': texto obtenido mediante OCR. Revisa caracteres, opciones y numeración en el original (confianza de lectura: '+Math.round(recognized.confidence)+'%).');}text+='\n[Página '+i+']\n'+pageText;onProgress(10+Math.round(i/pdf.numPages*85));}}catch(error:any){if(error?.name==='PasswordException')fail('El PDF está protegido por contraseña. Sube una copia sin cifrado.');throw error;}finally{if(worker)await worker.terminate();await loading.destroy();}
}
if(text.length>1000000)fail('El documento contiene demasiado texto. Divídelo en archivos más pequeños.');if(!text.trim()&&!embedded.length)fail('El documento no contiene texto legible ni preguntas. Comprueba el archivo original.');return {text,embedded,warnings,images};}
