import {reportEducationLevel,reportNextSteps} from '../student/report-route';
import {BaccalaureateResult} from '../student/BaccalaureateResult';
import {EcuadorExplorer} from '../student/EcuadorExplorer';
import {Dialog} from '../../components/ui/Dialog';
import {CareerOfferList} from '../student/ReportContext';
import {PdfViewer} from '../../components/ui/PdfViewer';
import {TestResult} from '../student/TestResult';
import {useCallback,useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,Download,FileText,Users,CheckCircle,ClipboardList} from 'lucide-react';
import {useSession,previewAction,refreshSession} from '../../lib/session';
import {Button,Notice,PageHeader,SelectField} from '../../components/ui/primitives';
import {professionalReport} from '../../lib/professional-report';
import {dimensions} from '../../data/instruments';
import {ReleaseResult} from './ReleaseResult';
import './admin-results.css';
import '../student/results-document.css';

const date=(v:string)=>v?new Date(v).toLocaleDateString('es-EC',{day:'numeric',month:'short',year:'numeric'}):'Sin actividad';
const name=(v:string)=>dimensions.find(d=>d.code===v)?.name||v;
const parse=(v:any)=>typeof v==='string'?JSON.parse(v):v;
function Pdf({report}:{report:any}){
 const[url,setUrl]=useState(''),[error,setError]=useState('');
 useEffect(()=>{let active=true,objectUrl='';setUrl('');setError('');professionalReport(report).then(doc=>{objectUrl=URL.createObjectURL(doc.output('blob'));if(active)setUrl(objectUrl);else URL.revokeObjectURL(objectUrl);}).catch(()=>{if(active)setError('No se pudo preparar el PDF. Vuelve a abrir este informe.');});return()=>{active=false;if(objectUrl)URL.revokeObjectURL(objectUrl);};},[report]);
 return <section className="ar-pdf"><header><div><h3>Documento del estudiante</h3><p>Informe {report.version} · {date(report.createdAt)} · Mismo reporte disponible en su cuenta.</p></div>{url&&<div className="ar-actions"><a className="button button--primary" href={url} download={'informe-'+report.id+'.pdf'}><Download size={16}/>Descargar PDF</a><a className="button button--secondary" href={url} target="_blank" rel="noreferrer">Abrir e imprimir</a></div>}</header>{error?<Notice tone="danger">{error}</Notice>:url?<PdfViewer title="Informe del estudiante" src={url}/>:<p role="status">Preparando documento…</p>}</section>;
}
function Scores({submission}:{submission:any}){if(submission.evaluation)return <TestResult key={submission.id+':'+submission.evaluation.revision} submission={submission} admin/>;const scores=parse(submission.scores)||[],instrument=parse(submission.snapshot);return <div className="ar-scores">{scores.map((s:any)=>{const max=submission.instrument_id==='intereses'?25:submission.instrument_id==='autoconocimiento'?100:0;const value=submission.instrument_id==='autoconocimiento'?s.percent:instrument.aggregation==='sum'||max?s.raw:s.value;return <div key={s.dimension}><div><span>{name(s.dimension)}</span><strong>{value}{max?' / '+max:instrument.aggregation==='sum'?' · suma':' · promedio'}</strong></div>{max>0&&<meter min={0} max={max} value={value} aria-label={name(s.dimension)}/>}</div>;})}{!scores.length&&<p>Esta entrega contiene respuestas para revisión, sin puntuación automática.</p>}</div>;}
function Answers({submission}:{submission:any}){const instrument=parse(submission.snapshot),answers=parse(submission.answers);return <details className="ar-answers"><summary>Consultar respuestas guardadas</summary><ol>{instrument.questions.map((q:any)=><li key={q.id}><strong>{q.text}</strong><p>{q.type==='open'?String(answers[q.id]??'Sin respuesta'):(q.options||instrument.options||[]).filter((o:any)=>Array.isArray(answers[q.id])?answers[q.id].includes(o.value):answers[q.id]===o.value).map((o:any)=>o.label).join(', ')||'Sin respuesta'}</p></li>)}</ol></details>;}

export function AdminResults(){
 const [refreshing,setRefreshing]=useState(false);
 const [career,setCareer]=useState<any>(null);
 const session=useSession(),[reports,setReports]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[selected,setSelected]=useState(''),[tab,setTab]=useState('resumen'),[version,setVersion]=useState(''),[page,setPage]=useState(1);
 const load=useCallback(async()=>{try{const data=await previewAction('reports/guidance');setReports(data.items||[]);setError('');}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load,session.values['rv360:submissions']]);
 useEffect(()=>{if(!reports.some(r=>r.status==='processing'))return;const t=setInterval(()=>void load(),3000);return()=>clearInterval(t);},[reports,load]);
 const submissions:any[]=session.values['rv360:submissions']||[],users:any[]=session.values['rv360:admin-users']||[];
 const students=new Map<string,any>();users.filter(u=>u.role==='Estudiante').forEach(u=>students.set(u.id,u));reports.forEach(r=>{if(!students.has(r.student.id))students.set(r.student.id,r.student);});
 const rows=Array.from(students.values()).map(u=>{const deliveries=submissions.filter(s=>s.user_id===u.id).sort((a,b)=>b.created_at.localeCompare(a.created_at));const saved=reports.filter(r=>r.student.id===u.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));return {...u,deliveries,saved,latest:saved[0],pending:deliveries.filter(s=>s.resultReleased===false).length};}).sort((a,b)=>(b.deliveries[0]?.created_at||'').localeCompare(a.deliveries[0]?.created_at||'')||a.name.localeCompare(b.name));
 const withReport=rows.filter(r=>r.saved.some((s:any)=>s.status==='available')).length,withTests=rows.filter(r=>r.deliveries.length).length,pending=rows.filter(r=>r.pending).length;
 const filtered=rows.filter(r=>(r.name+' '+(r.email||'')).toLocaleLowerCase().includes(query.toLocaleLowerCase())&&(filter==='all'||filter==='report'&&r.saved.some((s:any)=>s.status==='available')||filter==='pending'&&r.pending||filter==='empty'&&!r.deliveries.length));
 const pages=Math.max(1,Math.ceil(filtered.length/10)),currentPage=Math.min(page,pages),student=rows.find(r=>r.id===selected),report=student?.saved.find((r:any)=>r.id===version)||student?.latest;
 const level=reportEducationLevel(report,student?.profile||student),school=level==='bachillerato';
 useEffect(()=>{setTab('resumen');setCareer(null);},[report?.id,level]);
 const tests=new Map<string,{title:string;students:Set<string>;attempts:number}>();submissions.forEach(s=>{const item=tests.get(s.instrument_id)||{title:parse(s.snapshot).title,students:new Set<string>(),attempts:0};item.students.add(s.user_id);item.attempts++;tests.set(s.instrument_id,item);});
 function open(id:string){setSelected(id);setTab('resumen');setVersion('');window.scrollTo({top:0,behavior:'instant'});}
 return <div className="ar-page">{error&&<Notice tone="danger">{error}</Notice>}{student?<>
 <Button variant="ghost" icon={<ArrowLeft size={16}/>} onClick={()=>setSelected('')}>Volver a estudiantes</Button>
 <PageHeader title={student.name} description={student.email||'Ficha de resultados del estudiante'}/>
 <Button variant="secondary" loading={refreshing} onClick={async()=>{setRefreshing(true);setError('');try{const updated=await previewAction('reports/guidance',{method:'POST',body:JSON.stringify({studentId:student.id})});await load();setVersion(updated.id);}catch(e){setError((e as Error).message);}finally{setRefreshing(false);}}}>Actualizar orientación de {school?'bachillerato':'universidad'}</Button>
 {!report?.partial&&report?.ai?.status&&report.ai.status!=='available'&&<Notice tone="warning">Análisis con IA pendiente: {report.ai.error?.message||'Actualiza la orientación para volver a intentar el análisis.'}</Notice>}
 <div className="ar-student-meta"><span>{student.deliveries.length} entregas</span><span>{student.saved.length} versiones de informe</span><span>Última entrega: {date(student.deliveries[0]?.created_at)}</span></div>
 <nav className="ar-tabs" aria-label="Secciones de la ficha">{[['resumen','Resumen'],school?['bachillerato','Bachillerato']:['universidad','Universidad'],['recomendaciones','Recomendaciones'],['evaluaciones','Evaluaciones'],['informes','Informes y PDF']].map(([id,label])=><button key={id} aria-current={tab===id?'page':undefined} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {school&&tab==='bachillerato'&&(report?.analysis?.pathway?<BaccalaureateResult readiness={report.readiness?.bachillerato} pathway={report.analysis.pathway}/>:<Notice>La orientación de bachillerato aparecerá cuando el estudiante entregue los tests y se actualice su informe.</Notice>)}
 {!school&&tab==='universidad'&&(report?<div className="rd-root"><EcuadorExplorer report={report} onOpen={setCareer}/></div>:<Notice>Las opciones universitarias aparecerán cuando el estudiante tenga un informe disponible.</Notice>)}
 {tab==='recomendaciones'&&(report?<section className="ad-panel"><h2>Recomendaciones para el estudiante</h2><ol>{reportNextSteps(report,student?.profile||student).map(step=><li key={step}>{step}</li>)}</ol></section>:<Notice>Las recomendaciones aparecerán con los resultados del estudiante.</Notice>)}
 {!school&&<Dialog wide open={!!career} title={(report?.catalog||[]).find((c:any)=>c.id===career?.careerId)?.name||'Explorar carrera'} onClose={()=>setCareer(null)}>{career&&<div className="stack"><h3>Por qué conviene explorarla</h3><p>{career.reason}</p><h3>Qué estudiar y comparar</h3><p>{career.explore}</p><CareerOfferList offers={report?.offers?.[career.careerId]||[]}/></div>}</Dialog>}
 {tab==='resumen'&&<div className="ar-detail-grid"><section className="ad-panel"><h2>Seguimiento individual</h2><p>Consulta las entregas y el informe guardado de este estudiante.</p><div className="ar-checklist"><div><ClipboardList size={20}/><span><strong>{new Set(student.deliveries.map((s:any)=>s.instrument_id)).size} tests entregados</strong><small>Los intentos repetidos se conservan en Evaluaciones.</small></span></div><div><FileText size={20}/><span><strong>{report?(report.partial?'Informe parcial':'Informe guardado'):'Sin informe todavía'}</strong><small>{report?`${report.progress?.submitted||report.instruments.length} de ${report.progress?.total||report.instruments.length} tests incluidos · ${date(report.createdAt)}`:'Se mostrará cuando el estudiante tenga resultados disponibles.'}</small></span></div><div><CheckCircle size={20}/><span><strong>{student.pending?`${student.pending} resultados pendientes de publicación`:'Sin publicaciones pendientes'}</strong><small>La revisión de resultados se realiza desde Evaluaciones.</small></span></div></div><Button variant="secondary" onClick={()=>setTab('evaluaciones')}>Revisar evaluaciones <ArrowRight size={16}/></Button></section><section className="ad-panel"><h2>Orientación del último informe</h2>{report?.analysis?<><p>{report.analysis.highlightedDimensions?.map(name).join(' · ')}</p><p>{report.analysis.summary}</p>{report.ai?.status==='available'&&<p className="ar-muted">Análisis de los resultados asistido por IA.</p>}<p className="ar-muted">Intereses declarados, no una medición de aptitud ni una decisión de carrera.</p>{school?<><h3>Modalidad y figuras de bachillerato recomendadas</h3><p>{report.analysis.pathway?.title||'Orientación pendiente'}</p><p>{report.analysis.pathway?.reason}</p><ul className="ar-careers">{[...(report.analysis.pathway?.science||[]),...(report.analysis.pathway?.technical||[])].map((option:any)=><li key={option.id}><details><summary>{option.name}</summary><p>{option.reason}</p><p><strong>Qué estudiar: </strong>{option.subjects}</p><p>{option.activity}</p></details></li>)}</ul></>:<><h3>Carreras universitarias para explorar</h3>{!report.analysis.recommendations?.length&&<p className="ar-muted">Este informe todavía no propone carreras. Revisa los tests incluidos y las explicaciones del documento.</p>}<ul className="ar-careers">{(report.analysis.recommendations||[]).map((r:any)=><li key={r.careerId}><details><summary>{(report.catalog||[]).find((c:any)=>c.id===r.careerId)?.name||r.careerId}</summary><p>{r.reason}</p><p><strong>Qué explorar: </strong>{r.explore}</p></details></li>)}</ul></>}<Button onClick={()=>setTab('informes')}>Consultar informe <ArrowRight size={16}/></Button></>:<p>No hay una orientación publicada para esta persona. Sus entregas disponibles se pueden consultar por separado.</p>}</section></div>}
 {tab==='evaluaciones'&&<section><h2>Entregas y resultados</h2><p className="ar-muted">Historial exclusivo de {student.name}. Cada entrega conserva las preguntas y la versión utilizada.</p>{student.deliveries.map((s:any)=><article className="ad-panel" key={s.id}><header><div><h3>{parse(s.snapshot).title}</h3><p>{date(s.created_at)} · {s.resultReleased===false?'Pendiente de publicación':'Resultado publicado'}</p></div></header><ReleaseResult id={s.id} released={s.resultReleased} onReleased={()=>void refreshSession()}/><Scores submission={s}/><Answers submission={s}/></article>)}{!student.deliveries.length&&<div className="ar-empty">Este estudiante todavía no ha entregado tests.</div>}</section>}
 {tab==='informes'&&(report?<><div className="ar-report-picker"><SelectField label="Versión del informe" value={report.id} onChange={e=>setVersion(e.target.value)}>{student.saved.map((r:any)=><option key={r.id} value={r.id}>Informe {r.version} · {date(r.createdAt)}{r.partial?' · Parcial':''}</option>)}</SelectField><p>Las versiones conservan el contenido utilizado en cada informe.</p></div>{report.partial&&<Notice>Informe parcial: incluye {report.progress?.submitted||report.instruments.length} de {report.progress?.total||report.instruments.length} tests. Las opciones pueden cambiar al completar las evaluaciones.</Notice>}<Pdf key={report.id} report={report}/></>:<div className="ar-empty">No hay informes guardados para este estudiante. Consulta sus entregas en Evaluaciones.</div>)}
 </>:<><PageHeader title="Resultados e informes" description="Seguimiento por estudiante, desde la entrega de tests hasta su informe de orientación."/>
 <div className="ad-kpis">{[[Users,rows.length,'Estudiantes','Personas en el alcance administrativo'],[ClipboardList,withTests,'Con entregas','Al menos un test entregado'],[FileText,withReport,'Con informe disponible','Personas, no versiones de informes'],[CheckCircle,pending,'Requieren publicación','Estudiantes con resultados por publicar']].map(([Icon,count,label,hint]:any)=><article key={label}><span className="ad-kpi-icon"><Icon size={20}/></span><div><p>{label}</p><strong>{count}</strong><small>{hint}</small></div></article>)}</div>
 <div className="ar-bi"><section className="ad-panel"><h2>Cobertura de informes</h2><div className="ar-coverage"><strong>{rows.length?Math.round(withReport/rows.length*100):0}%</strong><span>{withReport} de {rows.length} estudiantes con informe disponible</span></div><meter min={0} max={Math.max(1,rows.length)} value={withReport} aria-label="Cobertura de informes"/><p className="ar-muted">Indicador de seguimiento del proceso; no representa capacidad ni aptitud.</p></section><section className="ad-panel"><h2>Participación por test</h2>{Array.from(tests.entries()).sort((a,b)=>b[1].students.size-a[1].students.size).slice(0,4).map(([id,t])=><div className="ar-test-bar" key={id}><span>{t.title}</span><strong>{t.students.size} estudiantes</strong><meter min={0} max={Math.max(1,rows.length)} value={t.students.size} aria-label={t.title}/></div>)}{!tests.size&&<p className="ar-muted">Los indicadores aparecerán con las primeras entregas.</p>}</section></div>
 <section className="ad-panel ar-directory"><header><div><h2>Estudiantes y seguimiento</h2><p>Abre una ficha para revisar respuestas, resultados e informes.</p></div></header><div className="ar-filters"><div className="field"><label htmlFor="ar-search">Buscar estudiante</label><input id="ar-search" type="search" placeholder="Nombre o correo electrónico" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/></div><SelectField label="Seguimiento" value={filter} onChange={e=>{setFilter(e.target.value);setPage(1);}}><option value="all">Todos los estudiantes</option><option value="report">Con informe disponible</option><option value="pending">Pendientes de publicación</option><option value="empty">Sin entregas</option></SelectField></div>
 {loading?<p role="status">Cargando informes guardados…</p>:<><div className="ar-table"><table><thead><tr><th>Estudiante</th><th>Tests entregados</th><th>Informe</th><th>Última entrega</th><th><span className="sr-only">Acción</span></th></tr></thead><tbody>{filtered.slice((currentPage-1)*10,currentPage*10).map(r=><tr key={r.id}><td><strong>{r.name}</strong><small>{r.email}</small></td><td data-label="Tests entregados">{new Set(r.deliveries.map((s:any)=>s.instrument_id)).size}{r.pending>0&&<small>{r.pending} por publicar</small>}</td><td data-label="Informe"><span className={'ar-status '+(r.latest?'ar-status--ready':'')}>{r.latest?(r.latest.status==='available'?(r.latest.partial?'Parcial':'Disponible'):r.latest.status==='processing'?'En preparación':'Pendiente'):'Sin informe'}</span></td><td data-label="Última entrega">{date(r.deliveries[0]?.created_at)}</td><td><Button variant="secondary" onClick={()=>open(r.id)} aria-label={'Ver ficha de '+r.name}>Ver ficha <ArrowRight size={15}/></Button></td></tr>)}</tbody></table></div>{!filtered.length&&<div className="ar-empty">No hay estudiantes que coincidan con estos filtros.</div>}<footer className="ar-pagination"><span>{filtered.length} estudiantes · Página {currentPage} de {pages}</span><div><Button variant="ghost" disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}>Anterior</Button><Button variant="ghost" disabled={currentPage===pages} onClick={()=>setPage(currentPage+1)}>Siguiente</Button></div></footer></>}
 </section></>}</div>;
}
