import {useState} from 'react';
import {KeyRound} from 'lucide-react';
import {previewAction} from '../../lib/session';
import {Button,PasswordInput,Notice} from '../../components/ui/primitives';
import {Dialog} from '../../components/ui/Dialog';

export function ResetUserPassword({user}:{user:{id:string;name:string;email:string}}){
 const[open,setOpen]=useState(false),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false);
 async function reset(){setError('');if(password.length<15||password.length>128){setError('Usa una contraseña de 15 a 128 caracteres.');return;}if(password!==confirm){setError('Las contraseñas no coinciden.');return;}setBusy(true);try{await previewAction('admin/users',{method:'POST',body:JSON.stringify({action:'reset-password',id:user.id,password,confirmPassword:confirm})});setPassword('');setConfirm('');setOpen(false);setDone(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="stack-sm" style={{marginTop:16}}>{done&&<Notice tone="success">Contraseña restablecida. Las sesiones anteriores se cerraron. Comparte la nueva contraseña por un canal privado.</Notice>}<Button variant="secondary" icon={<KeyRound size={17}/>} onClick={()=>{setPassword('');setConfirm('');setError('');setOpen(true);}}>Restablecer contraseña</Button><Dialog open={open} title="Restablecer contraseña" onClose={()=>{if(!busy){setOpen(false);setPassword('');setConfirm('');}}}><div className="stack"><p>Define una nueva contraseña para <strong>{user.name}</strong>.<br/><span className="muted small">{user.email}</span></p><PasswordInput label="Nueva contraseña" autoComplete="new-password" minLength={15} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)} hint="Entre 15 y 128 caracteres."/><PasswordInput label="Confirmar nueva contraseña" autoComplete="new-password" maxLength={128} value={confirm} onChange={e=>setConfirm(e.target.value)}/><Notice tone="neutral">Se cerrarán las sesiones abiertas y se invalidarán los enlaces anteriores de recuperación. El estado de la cuenta y sus resultados se conservan. Este cambio se aplica por separado de “Guardar usuario”.</Notice>{error&&<Notice tone="danger">{error}</Notice>}<div className="row"><Button loading={busy} onClick={()=>void reset()}>Confirmar nueva contraseña</Button><Button variant="secondary" disabled={busy} onClick={()=>{setOpen(false);setPassword('');setConfirm('');}}>Cancelar</Button></div></div></Dialog></div>;
}
