import {StudyOptionSuggestions} from './StudyOptionSuggestions';
import {defaultPreparationLevel,schoolTarget,schoolTrainingTargets} from '../../data/school-training';
import {exactTestLevel,testLevelLabel} from './test-manager-level';
import {previewAction} from '../../lib/session';
import {useEffect,useState} from 'react';
import type {Instrument,Question} from '../../types';
import {Button,Card,Field,SelectField,TextareaField,Notice} from '../../components/ui/primitives';
import {QUESTION_TYPES} from '../../lib/test-engine';
const uid=()=>crypto.randomUUID();
export function AudienceSettings({test,users,onChange}:{test:Instrument;users:{id:string;name:string;role:string;stage?:string}[];onChange:(v:Partial<Instrument>)=>void}){
 const[search,setSearch]=useState('');
 const category=exactTestLevel(test.educationLevel)||'universidad';
 return <div className="stack-sm"><p className="small"><strong>Categoría: {testLevelLabel(category)}</strong>. Se conserva durante toda la edición.</p><SelectField label="¿Quién puede realizar este test?" value={test.audience||'all'} onChange={e=>onChange({audience:e.target.value as 'all'|'selected',studentIds:e.target.value==='all'?[]:test.studentIds||[]})}><option value="all">Todos los estudiantes de esta categoría</option><option value="selected">Seleccionar estudiantes</option></SelectField>{test.audience==='selected'&&<><Field label="Buscar estudiante para asignar" type="search" value={search} onChange={e=>setSearch(e.target.value)}/><fieldset className="audience-list"><legend>{test.studentIds?.length||0} estudiantes seleccionados</legend>{users.filter(u=>u.role==='Estudiante'&&defaultPreparationLevel(u)===category&&u.name.toLocaleLowerCase().includes(search.toLocaleLowerCase())).map(u=><label key={u.id}><input type="checkbox" checked={test.studentIds?.includes(u.id)||false} onChange={e=>onChange({studentIds:e.target.checked?[...(test.studentIds||[]),u.id]:(test.studentIds||[]).filter(id=>id!==u.id)})}/>{u.name}</label>)}</fieldset></>}</div>;
}
export function QuestionFormat({test,q,onChange}:{test:Instrument;q:Question;onChange:(v:Partial<Question>)=>void}){
 return <div className="stack"><Field label="Sección (opcional)" value={q.section||''} onChange={e=>onChange({section:e.target.value})}/><TextareaField label="Ayuda para responder (opcional)" value={q.help||''} onChange={e=>onChange({help:e.target.value})}/><label><input type="checkbox" checked={q.required!==false} onChange={e=>onChange({required:e.target.checked})}/> Respuesta obligatoria</label>
 {['multiple','matrix'].includes(q.type||'')&&<div className="grid grid-2"><Field label="Mínimo de selecciones" type="number" min={1} value={q.minSelections??1} onChange={e=>onChange({minSelections:Number(e.target.value)})}/><Field label="Máximo de selecciones" type="number" min={1} value={q.maxSelections??(q.options||test.options).length} onChange={e=>onChange({maxSelections:Number(e.target.value)})}/><SelectField label="Opción exclusiva (opcional)" value={q.exclusiveValue??''} onChange={e=>onChange({exclusiveValue:e.target.value===''?undefined:Number(e.target.value)})}><option value="">Ninguna</option>{(q.options||test.options).map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</SelectField></div>}
 {q.type==='number'&&<div className="grid grid-2">{(['min','max','step'] as const).map((key,i)=><Field key={key} label={['Mínimo','Máximo','Paso'][i]} type="number" step="any" value={q[key]??''} onChange={e=>onChange({[key]:e.target.value===''?undefined:Number(e.target.value)})}/>)}<Field label="Unidad (opcional)" value={q.unit||''} onChange={e=>onChange({unit:e.target.value})}/></div>}
 {['open','short'].includes(q.type||'')&&<div className="grid grid-2"><Field label="Mínimo de caracteres" type="number" min={0} value={q.minLength??1} onChange={e=>onChange({minLength:Number(e.target.value)})}/><Field label="Máximo de caracteres" type="number" min={1} value={q.maxLength??10000} onChange={e=>onChange({maxLength:Number(e.target.value)})}/></div>}
 {q.type==='matrix'&&<div className="stack-sm"><p className="small muted">Cada fila se evalúa con estas opciones. Las puntuaciones de las filas se suman antes de aplicar el peso de la pregunta.</p><label><input type="checkbox" checked={!!q.matrixMultiple} onChange={e=>onChange({matrixMultiple:e.target.checked})}/> Varias opciones por fila</label>{q.rows?.map((r,i)=><div className="row" key={r.id}><Field label={'Fila '+(i+1)} value={r.label} onChange={e=>onChange({rows:q.rows!.map(x=>x.id===r.id?{...x,label:e.target.value}:x)})}/><Button variant="ghost" onClick={()=>onChange({rows:q.rows!.filter(x=>x.id!==r.id)})}>Quitar fila</Button></div>)}<Button variant="secondary" onClick={()=>onChange({rows:[...(q.rows||[]),{id:uid(),label:''}]})}>Añadir fila</Button></div>}
 <details className="te-advanced"><summary>Mostrar según una respuesta anterior</summary><SelectField label="Mostrar esta pregunta si…" value={q.visibleWhen?.questionId||''} onChange={e=>onChange({visibleWhen:e.target.value?{questionId:e.target.value,operator:'equals',value:''}:undefined})}><option value="">Mostrar siempre</option>{test.questions.filter(x=>x.id!==q.id&&['single','multiple','likert','yesno'].includes(x.type||'likert')).map(x=><option key={x.id} value={x.id}>{x.text||'Sin enunciado'}</option>)}</SelectField>{q.visibleWhen&&<><SelectField label="Condición" value={q.visibleWhen.operator} onChange={e=>onChange({visibleWhen:{...q.visibleWhen!,operator:e.target.value as 'equals'}})}><option value="equals">Es igual a</option><option value="notEquals">Es diferente de</option><option value="includes">Incluye</option></SelectField><SelectField label="Respuesta" value={q.visibleWhen.value} onChange={e=>onChange({visibleWhen:{...q.visibleWhen!,value:e.target.value===''?'':Number(e.target.value)}})}><option value="">Selecciona una opción</option>{(test.questions.find(x=>x.id===q.visibleWhen!.questionId)?.options||test.options).map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</SelectField></>}</details></div>;
}
export function UniversalResults({test,onChange,questionIndex,onQuestionChange}:{test:Instrument;onChange:(v:Partial<Instrument>)=>void;questionIndex?:number;onQuestionChange?:(index:number)=>void}){
 const school=test.educationLevel==='bachillerato';
 const[careers,setCareers]=useState<{id:string;name:string}[]>([]),[query,setQuery]=useState('');
 useEffect(()=>{let active=true;setQuery('');setCareers([]);if(school){setCareers(schoolTrainingTargets.map(target=>({id:target.id,name:target.name})));return;}previewAction('admin/tests/careers').then(result=>{if(active)setCareers((result.careers||[]).filter((career:any)=>!schoolTarget(career.id)));}).catch(()=>{});return()=>{active=false;};},[school]);
 const change=(q:Question,patch:Partial<Question>)=>onChange({questions:test.questions.map(x=>x.id===q.id?{...x,...patch}:x)});
 return <div className="stack"><Notice tone="neutral">Configura las reglas documentadas de tu instrumento. Los resultados describen lo medido; no son porcentajes de aptitud ni garantías de éxito.</Notice><div className="grid grid-2"><SelectField label="Agregación" value={test.aggregation||'sum'} onChange={e=>onChange({aggregation:e.target.value as 'sum'|'mean'})}><option value="sum">Suma ponderada</option><option value="mean">Media ponderada (divide por suma de pesos)</option></SelectField><Field label="Cobertura mínima para resultado completo (%)" type="number" min={0} max={100} value={test.minimumCoverage??0} onChange={e=>onChange({minimumCoverage:Number(e.target.value)})}/></div><label><input type="checkbox" checked={!!test.normalize} onChange={e=>onChange({normalize:e.target.checked})}/> Mostrar posición dentro del recorrido de la escala (0–100)</label>
 <details className="te-advanced" open={test.scoring==='dimensions'}><summary>Dimensiones del instrumento</summary><p className="small muted">Los identificadores se conservan aunque cambies el nombre.</p>{test.dimensions?.map(d=><div className="row" key={d.id}><Field label="Nombre de la dimensión" value={d.name} onChange={e=>onChange({dimensions:test.dimensions!.map(x=>x.id===d.id?{...x,name:e.target.value}:x)})}/><Button variant="ghost" disabled={test.questions.some(q=>(q.options||test.options).some(o=>d.id in (o.contributions||{})))} onClick={()=>onChange({dimensions:test.dimensions!.filter(x=>x.id!==d.id)})}>Eliminar dimensión</Button></div>)}<Button variant="secondary" onClick={()=>onChange({dimensions:[...(test.dimensions||[]),{id:uid(),name:''}]})}>Añadir dimensión</Button><p className="small muted">Para eliminar una dimensión, retira primero sus contribuciones en las preguntas.</p></details>
 <details className="te-advanced"><summary>{school?'Relaciones con modalidades y figuras de Bachillerato (opcional)':'Relaciones con carreras para explorar (opcional)'}</summary><p className="small muted">Cada relación necesita un criterio y fuente propios del instrumento. No establece una decisión definitiva.</p><StudyOptionSuggestions test={test} careers={careers} onSelect={careerId=>onChange({careerLinks:[...(test.careerLinks||[]),{id:uid(),careerId,dimensionId:'General',min:0,max:0,reason:'',source:''}]})}/><Field label={school?'Buscar modalidad o figura de Bachillerato':'Buscar carrera en el catálogo CES'} type="search" value={query} onChange={e=>setQuery(e.target.value)}/>{test.careerLinks?.map(link=><Card className="stack" key={link.id}>{link.careerId&&schoolTarget(link.careerId)!==school&&<Notice tone="warning">Esta relación pertenece a otra categoría. Selecciona una opción de {school?'Bachillerato':'Universidad'} o elimina la relación antes de publicar.</Notice>}<SelectField label={school?'Modalidad o figura de Bachillerato':'Carrera'} value={link.careerId} onChange={e=>onChange({careerLinks:test.careerLinks!.map(x=>x.id===link.id?{...x,careerId:e.target.value}:x)})}><option value="">Selecciona</option>{careers.filter(c=>c.id===link.careerId||c.name.toLocaleLowerCase().includes(query.toLocaleLowerCase())).map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</SelectField><SelectField label="Resultado relacionado" value={link.dimensionId} onChange={e=>onChange({careerLinks:test.careerLinks!.map(x=>x.id===link.id?{...x,dimensionId:e.target.value}:x)})}><option value="General">Total general</option>{test.dimensions?.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</SelectField><div className="grid grid-2">{(['min','max'] as const).map(key=><Field key={key} label={key==='min'?'Desde (incluido)':'Hasta (incluido)'} type="number" step="any" value={link[key]} onChange={e=>onChange({careerLinks:test.careerLinks!.map(x=>x.id===link.id?{...x,[key]:Number(e.target.value)}:x)})}/>)}</div><TextareaField label={school?'Por qué conviene explorar esta opción':'Por qué conviene explorar esta carrera'} value={link.reason} onChange={e=>onChange({careerLinks:test.careerLinks!.map(x=>x.id===link.id?{...x,reason:e.target.value}:x)})}/><Field label="Fuente del criterio de relación" value={link.source} onChange={e=>onChange({careerLinks:test.careerLinks!.map(x=>x.id===link.id?{...x,source:e.target.value}:x)})}/><Button variant="ghost" onClick={()=>onChange({careerLinks:test.careerLinks!.filter(x=>x.id!==link.id)})}>Eliminar relación</Button></Card>)}<Button variant="secondary" onClick={()=>onChange({careerLinks:[...(test.careerLinks||[]),{id:uid(),careerId:'',dimensionId:'General',min:0,max:0,reason:'',source:''}]})}>{school?'Añadir relación con Bachillerato':'Añadir relación con carrera'}</Button></details>
 {onQuestionChange&&<SelectField label="Configurar resultados de la pregunta" value={Math.min(questionIndex||0,Math.max(0,test.questions.length-1))} onChange={e=>onQuestionChange(Number(e.target.value))}>{test.questions.map((q,index)=><option key={q.id} value={index}>{index+1}. {q.text||'Pregunta sin enunciado'}</option>)}</SelectField>}
 {test.questions.map((q,index)=>{if(q.type==='info'||(onQuestionChange&&index!==Math.min(questionIndex||0,test.questions.length-1)))return null;const options=q.options||test.options,policy=q.policy||test.scoring||'manual';return <Card className="stack" key={q.id}><h3>{index+1}. {q.text||'Pregunta sin enunciado'}</h3><SelectField label="Cómo se evalúa esta pregunta" value={q.policy||''} onChange={e=>change(q,{policy:e.target.value as Question['policy']||undefined})}><option value="">Usar método del test</option><option value="none">Descriptiva · sin puntuación</option><option value="total">Puntos al total</option><option value="dimensions">Puntos por dimensiones</option><option value="objective">Clave de aciertos</option><option value="rubric">Rúbrica con revisión</option></SelectField><Field label="Peso de la pregunta" type="number" min={0} step="any" value={q.weight??1} onChange={e=>change(q,{weight:Number(e.target.value)})}/>
 {policy==='dimensions'&&<div className="stack-sm">{options.map(o=><fieldset className="preview-question" key={o.value}><legend>{o.label}</legend><div className="grid grid-2">{test.dimensions?.map(d=><Field key={d.id} label={d.name||'Dimensión sin nombre'} type="number" step="any" value={o.contributions?.[d.id]??''} onChange={e=>{const contributions={...o.contributions};if(e.target.value==='')delete contributions[d.id];else contributions[d.id]=Number(e.target.value);change(q,{options:options.map(x=>x.value===o.value?{...x,contributions}:x)});}}/>)}</div></fieldset>)}</div>}
 {q.type==='ranking'&&['dimensions','total'].includes(policy)&&<div className="grid grid-2">{options.map((o,i)=><Field key={o.value} label={'Multiplicador de posición '+(i+1)} type="number" step="any" value={q.rankingPoints?.[i]??''} onChange={e=>{const values=[...(q.rankingPoints||[])];values[i]=Number(e.target.value);change(q,{rankingPoints:values});}}/>)}</div>}
 {policy==='objective'&&<div className="stack-sm">{['single','multiple','yesno'].includes(q.type||'')&&<fieldset className="preview-question"><legend>Respuestas correctas</legend>{options.map(o=><label className="row" key={o.value}><input type={q.type==='multiple'?'checkbox':'radio'} name={'correct-'+q.id} checked={q.correctValues?.includes(o.value)||false} onChange={e=>change(q,{correctValues:q.type==='multiple'?(e.target.checked?[...(q.correctValues||[]),o.value]:(q.correctValues||[]).filter(n=>n!==o.value)):[o.value]})}/>{o.label}</label>)}</fieldset>}{q.type==='multiple'&&<><label><input type="checkbox" checked={!!q.partialCredit} onChange={e=>change(q,{partialCredit:e.target.checked})}/> Crédito parcial</label>{q.partialCredit&&<Field label="Penalización por opción incorrecta (fracción del máximo)" type="number" min={0.01} step={0.01} value={q.incorrectPenalty??''} onChange={e=>change(q,{incorrectPenalty:Number(e.target.value)})}/>}</>}{q.type==='short'&&<><TextareaField label="Respuestas aceptadas (una por línea)" value={(q.acceptedTexts||[]).join('\n')} onChange={e=>change(q,{acceptedTexts:e.target.value.split('\n')})}/><label><input type="checkbox" checked={!!q.normalizeText} onChange={e=>change(q,{normalizeText:e.target.checked})}/> Ignorar mayúsculas, tildes y espacios repetidos</label></>}{q.type==='number'&&<div className="grid grid-2"><Field label="Respuesta correcta desde (incluido)" type="number" step="any" value={q.numericKey?.min??''} onChange={e=>change(q,{numericKey:{min:Number(e.target.value),max:q.numericKey?.max??Number(e.target.value)}})}/><Field label="Hasta (incluido; igual para respuesta exacta)" type="number" step="any" value={q.numericKey?.max??''} onChange={e=>change(q,{numericKey:{min:q.numericKey?.min??Number(e.target.value),max:Number(e.target.value)}})}/></div>}</div>}
 {policy==='rubric'&&<div className="stack">{q.rubric?.map(r=><fieldset className="preview-question stack" key={r.id}><legend>Criterio de evaluación</legend><Field label="Criterio" value={r.label} onChange={e=>change(q,{rubric:q.rubric!.map(x=>x.id===r.id?{...x,label:e.target.value}:x)})}/>{r.levels.map(l=><div className="grid grid-2" key={l.id}><Field label="Nivel" value={l.label} onChange={e=>change(q,{rubric:q.rubric!.map(x=>x.id===r.id?{...x,levels:x.levels.map(n=>n.id===l.id?{...n,label:e.target.value}:n)}:x)})}/><Field label="Puntos" type="number" step="any" value={l.points} onChange={e=>change(q,{rubric:q.rubric!.map(x=>x.id===r.id?{...x,levels:x.levels.map(n=>n.id===l.id?{...n,points:Number(e.target.value)}:n)}:x)})}/></div>)}<Button variant="secondary" onClick={()=>change(q,{rubric:q.rubric!.map(x=>x.id===r.id?{...x,levels:[...x.levels,{id:uid(),label:'',points:0}]}:x)})}>Añadir nivel</Button><Button variant="ghost" onClick={()=>change(q,{rubric:q.rubric!.filter(x=>x.id!==r.id)})}>Eliminar criterio</Button></fieldset>)}<Button variant="secondary" onClick={()=>change(q,{rubric:[...(q.rubric||[]),{id:uid(),label:'',levels:[]}]})}>Añadir criterio de rúbrica</Button><p className="small muted">Administración debe evaluar cada criterio antes de entregar el resultado.</p></div>}
 </Card>;})}</div>;
}
