import {reportEducationLevel,reportNextSteps} from './report-route';
import {BaccalaureateResult} from './BaccalaureateResult';
import {PdfViewer} from '../../components/ui/PdfViewer';
import {useSession} from '../../lib/session';
import {EcuadorExplorer} from './EcuadorExplorer';
import {trainingApi} from '../training/shared';
import {useEffect,useState} from 'react';
import {ArrowDownToLine,ArrowUpRight,BookOpen,CheckCircle2,FileText,Info} from 'lucide-react';
import {professionalReport} from '../../lib/professional-report';
import {dimensions} from '../../data/instruments';
import {Button,Notice} from '../../components/ui/primitives';
import {Dialog} from '../../components/ui/Dialog';
import {CareerOfferList,CatalogContext} from './ReportContext';
import './results-document.css';

const dimensionName=(code:string)=>dimensions.find(d=>d.code===code)?.name||code;
const date=(value:string)=>new Date(value).toLocaleDateString('es-EC',{day:'numeric',month:'short',year:'numeric'});
function Scores({item}:{item:any}){return <div className="rd-scores">{item.scores.map((s:any)=>{const interest=item.instrumentId==='intereses',self=item.instrumentId==='autoconocimiento',value=interest?s.raw:self?s.percent:item.instrument.aggregation==='sum'?s.raw:s.value,max=interest?25:self?100:null;return <div key={s.dimension}><div><span>{dimensionName(s.dimension)}</span><strong>{Number(value.toFixed(2))}{max&&<small> / {max}</small>}</strong></div>{interest&&<small className="rd-score-explanation">{dimensions.find(d=>d.code===s.dimension)?.description} Promedio: {(s.raw/(s.answered||5)).toLocaleString('es-EC',{maximumFractionDigits:1})} / 5</small>}{max&&<meter min={interest?5:0} max={max} value={value} aria-label={dimensionName(s.dimension)}/>}</div>;})}</div>;}
function Answers({item}:{item:any}){return <dl className="rd-answers">{item.instrument.questions.map((q:any)=><div key={q.id}><dt>{q.text}</dt><dd>{q.type==='open'?item.answers[q.id]||'Sin respuesta opcional':(q.options||item.instrument.options||[]).filter((o:any)=>Array.isArray(item.answers[q.id])?item.answers[q.id].includes(o.value):item.answers[q.id]===o.value).map((o:any)=>o.label).join(', ')||'Sin respuesta opcional'}</dd></div>)}</dl>;}

export function GuidanceDocument({report}:{report:any}){
 const session=useSession();
 const level=reportEducationLevel(report,session.values['rv360:profile']),school=level==='bachillerato';
 const [tab,setTab]=useState('resumen'),[career,setCareer]=useState<any>(null),[pdf,setPdf]=useState(''),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{let active=true,url='';setPdf('');setError('');void professionalReport(report).then(doc=>{if(!active)return;url=URL.createObjectURL(doc.output('blob'));setPdf(url);}).catch(()=>{if(active)setError('No pudimos preparar el documento. Tus resultados siguen guardados.');});return()=>{active=false;if(url)URL.revokeObjectURL(url);};},[report,retry]);
 const selfKnowledge=report.instruments.find((s:any)=>s.instrumentId==='autoconocimiento'),interest=report.instruments.find((s:any)=>s.instrumentId==='intereses'),recommendations=school?[]:report.readiness?.universidad?.ready===false?[]:report.analysis?.recommendations||[],highlighted=report.analysis?.highlightedDimensions||[];
 const nextSteps=reportNextSteps(report,session.values['rv360:profile']);
 const optionCount=school?(report.analysis?.pathway?.science?.length||0)+(report.analysis?.pathway?.technical?.length||0):recommendations.length;
 useEffect(()=>{setTab('resumen');setCareer(null);},[level]);
 const followCareer=async(id:string)=>{try{await trainingApi('/goal',{careerIds:[id],fields:[]});window.location.assign('/mi-ruta/cursos/?carrera='+encodeURIComponent(id));}catch(e){setError((e as Error).message);}};
 const answerCount=report.instruments.reduce((n:number,s:any)=>n+s.instrument.questions.filter((q:any)=>s.answers[q.id]!==undefined).length,0);
 const viewer=<section className="rd-document" aria-labelledby="rd-pdf-title"><header><span className="rd-icon"><FileText size={20}/></span><div><h3 id="rd-pdf-title">Tu informe en PDF</h3><p>La misma información, lista para guardar.</p></div></header><div className="rd-pdf-actions">{pdf&&<><a href={pdf} download={'informe-ruta-'+report.id.slice(0,8)+'.pdf'}><ArrowDownToLine size={16}/>Descargar PDF</a><a href={pdf} target="_blank" rel="noreferrer"><ArrowUpRight size={16}/>Abrir e imprimir</a></>}</div>{error?<div className="rd-pdf-state"><Notice tone="danger">{error}</Notice><Button onClick={()=>setRetry(v=>v+1)}>Reintentar PDF</Button></div>:<div className="rd-frame"><PdfViewer title="Vista previa de tu informe PDF" src={pdf||undefined}/></div>}<footer>Cambia de página o amplía el documento con los controles del visor.</footer></section>;
 return <article className="rd-root">
  {report.historical&&<Notice>Estás consultando una versión histórica. Sus recomendaciones corresponden al perfil y a los resultados de esa fecha. Actualiza el reporte para consultar la orientación actual.</Notice>}
  <header className="rd-heading"><div><p>{report.student.name} <span>· {date(report.createdAt)}</span></p></div><span className={'rd-status '+(report.partial?'rd-status-partial':'')}><CheckCircle2 size={16}/>{report.partial?'Resultados iniciales':'Informe completo'}</span></header>
  {report.partial&&<div className="rd-progress"><div><strong>{report.progress?.submitted||report.instruments.length} de {report.progress?.total||report.instruments.length} tests disponibles en tu informe</strong><p>{report.partial?'Ya puedes explorar estos resultados. Completa los tests pendientes para ampliar tu orientación.':'Tus resultados están guardados. Puedes consultarlos y descargar el informe cuando quieras.'}</p></div>{report.partial&&<a href="/mi-ruta/evaluaciones">Continuar mis tests <ArrowUpRight size={16}/></a>}</div>}
  <nav className="rd-tabs" aria-label="Secciones de tus resultados">{[['resumen',school?'Bachillerato':'Universidad'],...(!school?[['catalogo','Carreras y universidades']]:[]),['recomendaciones','Recomendaciones'],['tests','Resultados por test'],['pdf','Informe PDF']].map(([id,label])=><button type="button" key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</nav>
  <div className={tab==='pdf'?'rd-pdf-full':tab==='catalogo'?'rd-catalog-full':'rd-content-full'}>
   {tab!=='pdf'&&<div className="rd-main">
    {tab==='catalogo'&&!school?<EcuadorExplorer report={{...report,analysis:{...report.analysis,recommendations}}} onOpen={setCareer} onFollow={session.user?.role==='student'?followCareer:undefined}/>:tab==='recomendaciones'?<section className="rd-panel rd-next"><BookOpen size={22}/><div><h3>Recomendaciones para tu ruta</h3>{school&&report.analysis?.pathway&&<><h4>{report.analysis.pathway.title}</h4><p>{report.analysis.pathway.reason}</p></>}{nextSteps.length?<ol>{nextSteps.map(step=><li key={step}>{step}</li>)}</ol>:<p>Completa los tests de {school?'Bachillerato':'Universidad'} y espera la publicación de sus resultados para recibir tu orientación.</p>}<div className="rd-follow-actions"><Button variant="secondary" onClick={()=>setTab(school?'resumen':'catalogo')}>{school?'Comparar Ciencias y Técnico':'Explorar carreras y universidades'}</Button></div></div></section>:tab==='resumen'?<>
     {school?(report.analysis?.pathway?<BaccalaureateResult readiness={report.readiness?.bachillerato} pathway={report.analysis.pathway}/>:<Notice>Actualiza el reporte para consultar tu orientación de bachillerato.</Notice>):report.readiness?.universidad?.ready===false?<Notice>Completa todos los tests de Universidad y espera la publicación de sus resultados para recibir tus carreras recomendadas.</Notice>:<EcuadorExplorer report={{...report,analysis:{...report.analysis,recommendations}}} onOpen={setCareer} onFollow={session.user?.role==='student'?followCareer:undefined}/> }
     <section className="rd-panel rd-intro"><span className="rd-eyebrow">LO QUE MUESTRAN TUS RESPUESTAS</span><h3>{highlighted.length?highlighted.map(dimensionName).join(' · '):interest?'Sigue explorando lo que te interesa':'Tu primer resultado ya está disponible'}</h3><p>{highlighted.length?'Estas son tus áreas de interés más altas, manteniendo los empates. Explora las opciones y contrástalas con experiencias antes de decidir.':report.analysis?.summary||'Revisa los resultados de tus tests y compáralos con tus experiencias.'}</p><div className="rd-mini-stats"><span><strong>{report.instruments.length}</strong> tests en el informe</span><span><strong>{answerCount}</strong> respuestas guardadas</span><span><strong>{optionCount}</strong> opciones para explorar</span></div></section>
     {!!report.analysis?.summary&&<section className="rd-panel"><h3>Análisis de tus respuestas</h3><p>{report.analysis.summary}</p></section>}
     {interest&&<section className="rd-panel"><div className="rd-section-title"><h3>Tus intereses, en perspectiva</h3><span>Escala de 5 a 25</span></div><Scores item={interest}/><p className="rd-caption"><Info size={15}/>Un valor más alto indica mayor interés declarado, no mayor capacidad.</p></section>}
     {selfKnowledge&&<section className="rd-panel"><div className="rd-section-title"><h3>Habilidades que reconoces en ti</h3><span>Tu autoconocimiento</span></div><p className="rd-section-copy">{school?'Compara estas fortalezas declaradas con las asignaturas y actividades de Ciencias y Técnico.':'Compara estas fortalezas declaradas con las asignaturas y actividades de las carreras sugeridas.'}</p><Scores item={selfKnowledge}/><p className="rd-caption">Frecuencia declarada, de 20 a 100. Revisa tus trabajos y experiencias con tu orientador para valorar tus aptitudes.</p></section>}

     {!!report.analysis?.selfReported?.length&&<details className="rd-disclosure"><summary>Lo que valoras al elegir</summary>{report.analysis.selfReported.map((v:any,i:number)=><p key={i}>{v.text}</p>)}</details>}
     <section className="rd-panel rd-next"><BookOpen size={22}/><div><h3>Tus recomendaciones</h3><p>{school?'Compara Ciencias y Técnico y sus áreas con tus intereses y conversa con tu orientador.':'Compara las carreras recomendadas, sus asignaturas y actividades con tus intereses y habilidades.'}</p><Button variant="secondary" onClick={()=>setTab('recomendaciones')}>Ver mis recomendaciones</Button></div></section>
    </>:<><div className="rd-section-title"><h3>Lo que respondiste en cada test</h3><span>{report.instruments.length} tests</span></div>{report.instruments.map((s:any)=><section className="rd-panel" key={s.id}><h3>{s.instrument.title}</h3><p className="rd-caption">Entregado el {date(s.createdAt)}</p>{s.scores.length?<><Scores item={s}/><p className="rd-caption">{s.instrumentId==='autoconocimiento'?'Frecuencias declaradas, de 20 a 100. No son porcentajes de aptitud.':s.instrumentId==='intereses'?'Suma de tus respuestas: de 5 a 25 por área.':'Puntuación calculada según las reglas de este test.'}</p><details><summary>Consultar mis respuestas</summary><Answers item={s}/></details></>:<Answers item={s}/>}</section>)}</>}
   </div>}
   {tab==='pdf'&&viewer}
  </div>
  {!report.partial&&report.ai?.status&&report.ai.status!=='available'&&<Notice tone="warning">Análisis con IA pendiente: {report.ai.error?.message||(report.ai.status==='pending'?'se está preparando el análisis de tus resultados.':'la conexión con el servicio no está disponible. Puedes actualizar el reporte para volver a intentarlo.')}</Notice>}
  <div className="rd-footnotes"><p><Info size={16}/>{report.ai?.status==='available'?'Análisis de tus resultados asistido por IA.':'Informe calculado a partir de tus respuestas guardadas.'}</p><details className="rd-disclosure"><summary>Cómo interpretar este informe</summary><p>Los tests describen tus intereses y preferencias. No determinan tu capacidad ni garantizan el éxito en una carrera.</p>{report.analysis?.limitations?.map((s:string)=><p key={s}>{s}</p>)}</details>{!school&&<CatalogContext report={report}/>}<details className="rd-disclosure"><summary>Información del informe guardado</summary><p>Versión {report.version} · {date(report.createdAt)} · Referencia {report.id}</p></details></div>
  {!school&&<Dialog wide open={!!career} title={(report.catalog||[]).find((c:any)=>c.id===career?.careerId)?.name||'Explorar carrera'} onClose={()=>setCareer(null)}>{career&&<div className="rd-career-detail"><h3>Por qué conviene explorarla</h3><p>{career.reason}</p><h3>Qué estudiar y comparar</h3><p>{career.explore}</p>{session.user?.role==='student'&&<Button onClick={()=>followCareer(career.careerId)}>Autopreparación</Button>}<CareerOfferList offers={career.filteredOffers||report.offers?.[career.careerId]||[]}/></div>}</Dialog>}
 </article>;
}
