import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {mkdirSync,mkdtempSync} from 'node:fs';
import {resolve} from 'node:path';
import {createRequire} from 'node:module';
mkdirSync('.qa-tools',{recursive:true});
const folder=mkdtempSync(resolve('.qa-tools','schools-'));
process.env.DB_DRIVER='sqlite';process.env.DATABASE_PATH=resolve(folder,'schools.sqlite');
const outfile=resolve(folder,'server.cjs');
await build({stdin:{contents:"export {schoolAction} from './lib/server/schools';export {manageUser} from './lib/server/admin-management';export {db,put,document,workspace} from './lib/server/store';",resolveDir:process.cwd(),loader:'ts'},bundle:true,platform:'node',format:'cjs',packages:'external',outfile,plugins:[{name:'marker',setup(b){b.onResolve({filter:/^server-only$/},()=>({path:'empty',namespace:'empty'}));b.onLoad({filter:/.*/,namespace:'empty'},()=>({contents:''}));}}]});
const {schoolAction,manageUser,db,put,document,workspace}=createRequire(import.meta.url)(outfile);
const admin={id:'admin',role:'admin',institutionId:'org',name:'Admin'},other={...admin,id:'other',institutionId:'other-org'};
const call=(suffix='',method='GET',body={},params={},user=admin)=>schoolAction(user,'admin/schools'+suffix,method,body,new URLSearchParams(params));
const draft={name:'Escuela Río Verde',code:'RV-01',city:'Quito',contact:'María Pérez',email:'maria@example.test',status:'Activa'};
try{
 await db.migrate();
 for(const [id,role,org] of [['student','student','org'],['counselor','orientador','org'],['foreign','student','other-org'],['admin','admin','org']])await db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,?,?)').run(id,id,id+'@example.test','hash',role,org,'','Activo');
 await put('student','rv360:profile',{institution:'Centro declarado',schoolId:'catalog-original'});
 for(const user of [null,{...admin,role:'student'},{...admin,role:'orientador'},{...admin,institutionId:null}])await assert.rejects(call('', 'GET',{}, {},user),e=>e.status===403);
 let a=(await call('','POST',draft)).school;
 await assert.rejects(call('','POST',{...draft,code:'rv-01'}),e=>e.status===409);
 await assert.rejects(call('','POST',{...draft,code:'BAD CODE'}),e=>e.status===400);
 await assert.rejects(call('','POST',{...draft,code:'RV-02',name:{}}),e=>e.status===400);
 assert.equal((await call('', 'GET',{}, {},other)).total,0);
 await assert.rejects(call('','POST',a,{},other),e=>e.status===404);
 await assert.rejects(call('/members','GET',{}, {schoolId:a.id},other),e=>e.status===404);
 const assign=(userId,schoolId,previousSchoolId=null)=>call('/assign','POST',{userId,schoolId,previousSchoolId});
 await assert.rejects(assign('foreign',a.id),e=>e.status===404);
 await assert.rejects(assign('admin',a.id),e=>e.status===404);
 await assign('student',a.id);await assign('counselor',a.id);
 let list=await call();assert.equal(list.items[0].students,1);assert.equal(list.items[0].counselors,1);
 assert.equal((await call('/members','GET',{}, {schoolId:a.id})).total,2);
 assert.equal((await call('/members','GET',{}, {schoolId:a.id,scope:'unassigned'})).total,0);
 assert.equal((await call('/members','GET',{}, {schoolId:a.id,scope:'all'})).total,2);
 assert.deepEqual(await document('student','rv360:profile'),{institution:'Centro declarado',schoolId:'catalog-original'});
 await assert.rejects(assign('student',null),e=>e.status===409);
 a=(await call('','POST',{...a,status:'Archivada'})).school;
 assert.equal((await call()).total,0);assert.equal((await call('','GET',{}, {status:'Archivada'})).total,1);
 assert.equal((await call('/members','GET',{}, {schoolId:a.id})).total,2);
 await assert.rejects(assign('student',a.id,a.id),e=>e.status===409);
 await assert.rejects(call('','POST',{...a,revision:1}),e=>e.status===409);
 await assign('student',null,a.id);
 a=(await call('','POST',{...a,status:'Activa',code:'RV-NEW'})).school;
 const b=(await call('','POST',draft)).school;
 await assign('student',b.id);
 await assign('student',a.id,b.id);
 assert.equal((await call('/members','GET',{}, {schoolId:b.id})).total,0);
 const attempts=await Promise.allSettled([call('','POST',{...a,city:'Uno'}),call('','POST',{...a,city:'Dos'})]);
 assert.equal(attempts.filter(r=>r.status==='fulfilled').length,1);assert.equal(attempts.find(r=>r.status==='rejected').reason.status,409);
 for(let i=0;i<21;i++)await call('','POST',{...draft,code:'PAGE-'+i,name:'Escuela página '+i});
 list=await call();assert.equal(list.items.length,20);assert.equal(list.total,23);
 const second=await call('','GET',{}, {page:'2'});assert.equal(second.items.length,3);assert(!second.items.some(s=>list.items.some(t=>s.id===t.id)));
 assert.equal((await call('','GET',{}, {q:'%'})).total,0);
 await assert.rejects(call('','GET',{}, {page:'-1'}),e=>e.status===400);
 await assert.rejects(call('','DELETE'),e=>e.status===405);
 const deletion=(school,user=admin)=>call('','POST',{action:'delete',id:school.id,revision:school.revision},{},user);
 let removable=(await call('','POST',{...draft,code:'DELETE-01'})).school;
 await assert.rejects(deletion(removable,other),e=>e.status===404);
 await assert.rejects(deletion({...removable,revision:0}),e=>e.status===409);
 await assign('student',removable.id,a.id);
 await assign('counselor',removable.id,a.id);
 const profileBefore=await document('student','rv360:profile');
 await deletion(removable);
 assert.equal(await document('schools:org',removable.id),null);
 assert.equal(await document('school-codes:org',removable.code),null);
 assert.equal(await document('school-members:org','student'),null);
 assert.equal(await document('school-members:org','counselor'),null);
 assert.equal((await db.prepare('SELECT id FROM users WHERE id=?').get('student')).id,'student');
 assert.deepEqual(await document('student','rv360:profile'),profileBefore);
 await assert.rejects(deletion(removable),e=>e.status===404);
 await assert.rejects(call('','POST',removable),e=>e.status===404,'A stale editor cannot recreate a deleted school');
 removable=(await call('','POST',{...draft,code:'DELETE-01'})).school;
 assert(removable.id,'Deleting frees the unique school code');
 await deletion(removable);
 await assert.rejects(call('','POST',{...draft,code:'BAD-ACTION',action:'unknown'}),e=>e.status===400);
 assert((await document('institution:org','rv360:audit')).some(e=>e.action==='Eliminar escuela'));
 assert((await document('institution:org','rv360:audit')).some(e=>e.action==='Asignar usuario a escuela'));
 await db.context(()=>manageUser(admin,{id:'student',action:'delete'}));assert.equal(await document('school-members:org','student'),null,'Deleting an unused account removes its assignment');
 const session=await workspace(admin);assert(!Object.keys(session.values).some(k=>k===a.id||k==='student'),'Directory is not copied to session data');
 console.log('PASS schools: admin-only, tenant isolation, validation, duplicate codes, revisions/concurrency, assignments, archive/reactivation, deletion preserving accounts/profiles, freed codes, stale-edit protection, pagination and audit.');
}finally{await db.close();}
